providers = ["php"]

[variables]
PHP_VERSION = "8.2"

[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.mbstring",
  "php82Extensions.pdo",
  "php82Extensions.pdo_mysql",
  "php82Extensions.curl",
  "php82Extensions.gd",
  "php82Extensions.zip",
  "php82Extensions.dom",
  "php82Extensions.ctype"
]

[phases.install]
cmds = [
  "if [ -f composer.json ]; then curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer; fi",
  "if [ -f composer.json ]; then composer install --no-dev --optimize-autoloader; fi"
]

[phases.build]
cmds = [
  "# Create a simple index.php router",
  "echo '<?php' > index.php",
  "echo '\\$uri = parse_url(\\$_SERVER[\"REQUEST_URI\"], PHP_URL_PATH);' >> index.php",
  "echo 'if (\\$uri === \"/\" || \\$uri === \"/index.html\") {' >> index.php",
  "echo '  if (file_exists(\"index.html\")) {' >> index.php", 
  "echo '    header(\"Content-Type: text/html\");' >> index.php",
  "echo '    readfile(\"index.html\");' >> index.php",
  "echo '    exit;' >> index.php",
  "echo '  }' >> index.php",
  "echo '}' >> index.php",
  "echo 'if (strpos(\\$uri, \"/api\") === 0) {' >> index.php",
  "echo '  \\$apiFile = \"./api\" . substr(\\$uri, 4);' >> index.php",
  "echo '  if (empty(substr(\\$uri, 4))) \\$apiFile = \"./api/index.php\";' >> index.php",
  "echo '  if (file_exists(\\$apiFile)) {' >> index.php",
  "echo '    chdir(dirname(\\$apiFile));' >> index.php", 
  "echo '    include \\$apiFile;' >> index.php",
  "echo '    exit;' >> index.php",
  "echo '  }' >> index.php",
  "echo '}' >> index.php",
  "echo 'http_response_code(404);' >> index.php",
  "echo 'echo \"404 Not Found\";' >> index.php",
  "echo '?>' >> index.php"
]

[start]
cmd = "php -S 0.0.0.0:8080 -t /app"
