providers = ["php"]

[variables]
PHP_VERSION = "8.2"
DOCUMENT_ROOT = "/"

[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.mbstring",
  "php82Extensions.pdo",
  "php82Extensions.pdo_mysql",
  "php82Extensions.pdo_pgsql", 
  "php82Extensions.mysqli",
  "php82Extensions.curl",
  "php82Extensions.gd",
  "php82Extensions.zip",
  "php82Extensions.xml",
  "php82Extensions.dom",
  "php82Extensions.session",
  "php82Extensions.tokenizer",
  "php82Extensions.ctype",
  "php82Extensions.fileinfo",
  "php82Extensions.json",
  "php82Extensions.openssl",
  "nginx"
]

[phases.install]
cmds = [
  "if [ -f composer.json ]; then curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer; fi",
  "if [ -f composer.json ]; then composer install --no-dev --optimize-autoloader; fi"
]

[phases.build]
cmds = [
  "mkdir -p /etc/nginx/conf.d",
  "mkdir -p public",
  "if [ ! -f public/index.php ] && [ ! -f index.php ]; then echo '<?php phpinfo(); ?>' > public/index.php; fi"
]

[start]
cmd = "php -S 0.0.0.0:8080 -t public"
